server:
  port: 8084

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?createDatabaseIfNotExist=true
    username: root
    password: Priti@05
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
      circuitbreaker:
        enabled: true
        group:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      DELIVERY-SERVICE:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
      TRACKING-SERVICE:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  timelimiter:
    instances:
      DELIVERY-SERVICE:
        timeout-duration: 3s
      TRACKING-SERVICE:
        timeout-duration: 3s

jwt:
  secret: smartcourier_jwt_secret_key_must_be_32_chars_min_123
  expiration: 86400000
