server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/gateway/deliveries/**
          filters:
            - StripPrefix=1
        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/gateway/tracking/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/gateway/admin/**
          filters:
            - StripPrefix=1
        - id: auth-service-docs
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/gateway/auth/v3/api-docs
          filters:
            - StripPrefix=2
        - id: delivery-service-docs
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/gateway/deliveries/v3/api-docs
          filters:
            - StripPrefix=2
        - id: tracking-service-docs
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/gateway/tracking/v3/api-docs
          filters:
            - StripPrefix=2
        - id: admin-service-docs
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/gateway/admin/v3/api-docs
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /gateway/auth/v3/api-docs
      - name: delivery-service
        url: /gateway/deliveries/v3/api-docs
      - name: tracking-service
        url: /gateway/tracking/v3/api-docs
      - name: admin-service
        url: /gateway/admin/v3/api-docs
