server:
  port: 8082
spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_db?createDatabaseIfNotExist=true
    username: root
    password: Priti@05
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
