server:
  port: 8083

spring:
  application:
    name: tracking-service
  datasource:
    url: jdbc:mysql://localhost:3306/tracking_db?createDatabaseIfNotExist=true
    username: root
    password: Priti@05
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

file:
  upload-dir: uploads/documents

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
way/admin/feign/deliveries
